spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/paymentdb
    username: payment
    password: paymentpw
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8081
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway
  endpoint:
    health:
      show-details: always
