spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/paymentdb
    username: payment
    password: paymentpw
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # 맵 키 defaultZone 은 camelCase 필수
  instance:
    hostname: localhost

server:
  port: 8081
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway
  endpoint:
    health:
      show-details: always
